version: '3'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  redis-stack-server:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"


