// automatically generated by the FlatBuffers compiler, do not modify

package com.example.demo.flatbuff;

@SuppressWarnings("unused")
public final class Any {
    private Any() {
    }

    public static final byte NONE = 0;
    public static final byte Monster = 1;

    public static final String[] names = {"NONE", "Monster",};

    public static String name(int e) {
        return names[e];
    }
}

