spring:
  kafka:
    bootstrap-servers: 3.7.20.38:29092
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/config?schema=pref
    username: postgres
    password: siddhary
  cloud:
    function:
      definition: messageCaptureBridge; feature1; feature2; messageCapture;
    stream:
      kafka:
        binder:
          brokers: 3.7.20.38:29092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.LongSerializer

      default-binder: kafka
      bindings:
        messageCaptureBridge-in-0:
          destination: order-channel
        feature1-in-0:
          destination: order-channel-odd
        feature2-in-0:
          destination: order-channel-even
