server:
  port: 8081

spring:
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
    database-platform: org.hibernate.dialect.ClickHouseDialect
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 10000
        order_updates: true


  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    username: default
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    hikari:
      auto-commit: true


  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    function:
      definition: transactions
    stream:
      kafka:
        binder:

          brokers: localhost:9092
          auto-add-partitions: true
          # transaction:
          #  transactionIdPrefix: tx-
          # producer-properties:
          #   partitioner.class: org.exmaple.flight-api.CustomPartitioner

      default-binder: kafka
      bindings:
        orderBuySupplier-out-0:
          destination: orders-buy-1
          producer:
            timeout: 10000
            partition-count: 1
        transactions-in-0:
          destination: orders-buy-1
          group: transactions
          consumer:
            partitioned: true
            concurrency: 1


